### ISSUE TITLE
../go/pkg/mod/github.com/templexxx/cpu@v0.1.0/cpu.go:93:14: undefined array length CacheLineSize or missing type constraint

### ISSUE THREAD

**Issue by SamZhang97** [templexxx/cpu#13]
I encountered an error while compiling frp using go. Please tell me how to solve it

**Comment by KatyushaScarlet** [comment]
Just change the package version in your go.mod to `master` , then run `go mod tidy` . Go will automatically upgrade the `cpu` package to the latest version of the master branch.
