### ISSUE TITLE
Should we bump this package version to v0.1.1?

### ISSUE THREAD

**Issue by KatyushaScarlet** [templexxx/cpu#14]
The loong64 is a new architecture supported since Go 1.19 and was added after the release of v0.1.0 of this cpu package. Some open-source projects (such as [frp](https://github.com/fatedier/frp/pull/4367)) prefer to import stable versions rather than the latest commits. I believe that adding support for loong64 might worth a minor version bump for this cpu package, making it more appealing for developers in the open-source community to use the cpu package on the new architecture.
Thank you!

**Comment by templexxx** [comment]
v0.1.1 has been released: https://github.com/templexxx/cpu/releases/tag/v0.1.1

releated:

https://github.com/templexxx/xorsimd/releases/tag/v0.4.3
