### ISSUE TITLE
../../templexxx/cpu/cpu_x86.go:9:23: CacheLineSize redeclared in this block,previous declaration at ../../templexxx/cpu/cpu_wasm.go:7:23

### ISSUE THREAD

**Issue by fwhezfwhez** [templexxx/cpu#3]
```
# github.com/templexxx/cpu
../../templexxx/cpu/cpu_x86.go:9:23: CacheLineSize redeclared in this block
	previous declaration at ../../templexxx/cpu/cpu_wasm.go:7:23
```

**Comment by templexxx** [comment]
Thank you!

But I wonder how to reproduce it? @fwhezfwhez 

I know nothing about wasm. But how could this happen? 
For Go, aren't they are different platform?

**Comment by fwhezfwhez** [comment]
go 1.9, 1.10 fail in travis-ci

**Comment by fwhezfwhez** [comment]
# github.com/templexxx/xor
../../../../pkg/mod/github.com/templexxx/xor@v0.0.0-20191217153810-f85b25db303b/xor_amd64.go:3:8: imported and not used: "github.com/templexxx/cpufeat" as cpu
../../../../pkg/mod/github.com/templexxx/xor@v0.0.0-20191217153810-f85b25db303b/xor_amd64.go:10:5: undefined: cpufeat

**Comment by fwhezfwhez** [comment]
I don't know either.

My project import `github.com\xtaci\kcp-go`
But this package import `github.com/templexxx/xor`, `././cpufeat`

I guess his repo might import different version of your packages and cause this bug.
