### ISSUE TITLE
支持下riscv64？

### ISSUE THREAD

**Issue by esrrhs** [templexxx/cpu#4]
会报错
cpu.go:94:14: undefined: CacheLineSize

**Comment by templexxx** [comment]
这就安排上 @esrrhs

**Comment by esrrhs** [comment]
> 
> 
> 这就安排上 @esrrhs

666

**Comment by templexxx** [comment]
或者你提个 PR 也行 :D

**Comment by esrrhs** [comment]
> 
> 
> 或者你提个 PR 也行 :D

我不太懂这个啊

**Comment by templexxx** [comment]
@esrrhs 应该可以了。你试下，我没有设备

**Comment by esrrhs** [comment]
> 
> 
> @esrrhs 应该可以了。你试下，我没有设备

666

**Comment by templexxx** [comment]
> > @esrrhs 应该可以了。你试下，我没有设备
> 
> 666

如果没问题了，麻烦你 close issue
