### ISSUE TITLE
Support for gcc-go?

### ISSUE THREAD

**Issue by RealXuChe** [templexxx/cpu#9]
Disclaimer: I'm not programming in go.

I see you including `textflag.h` [here](https://github.com/templexxx/cpu/blob/98168dcec14af3f8700bf309afe503bfe936e9f2/cpu_x86.s#L10), I suppose it's an implementation-specific header that can only use with Google's go compiler. The GNU implementation of go doesn't have it, could you please consider removing the use of this header if possible? I see that [klauspost/cpuid](https://github.com/klauspost/cpuid) didn't use this header. Or if it's impossible to remove the use of `textflag.h`, could you please consider adding another code to work with gcc-go?

---

事先声明：我没写过go
您的这些汇编文件里用了`textflag.h`，而就我所知这不是go标准内的头，这意味着只有Google的go编译器能编译这个库，而我在用GNU的go实现编译时就报错了。考虑到 [klauspost/cpuid](https://github.com/klauspost/cpuid)没有用到这个头，您能不能试着移除掉对`textflag.h`的依赖呢？又或者也许您可以考虑单独添加对gcc-go的支持？

**Comment by templexxx** [comment]
@RealXuChe Sorry for late, I'll do it soon

**Comment by templexxx** [comment]
@RealXuChe 

https://github.com/templexxx/cpu/pull/10

Could you try it? :D

**Comment by RealXuChe** [comment]
@templexxx 

Erm, I encountered this problem when compiling `frp`, and now I still can't compile it because the downstreams haven't updated their dependencies. I'll do the test after asking the downstreams to update their dependencies.
BTW, may you update the dep version of this package in github.com/templexxx/xorsimd?

-------

我是在编译frp的时候遇到这个问题的，现在因为下游的依赖版本都还没有更新，我还是没办法编译。我会去找下游更新依赖版本，然后测试一下的。
说到更新依赖版本，也请您更新一下你的github.com/templexxx/xorsimd里这个项目的依赖版本。

**Comment by templexxx** [comment]
@RealXuChe okay thank you for reminding

**Comment by templexxx** [comment]
@RealXuChe with the changes in https://github.com/templexxx/xorsimd/releases/tag/v0.4.2, no NOSPLIT anymore
